<?php
namespace Helper;

// here you can define custom actions
// all public methods declared in helper class will be available in $I

use Codeception\TestInterface;

class Api extends \Codeception\Module
{

    public $accessToken;

    public function _before(TestInterface $test)
    {
        \Artisan::call('migrate:fresh');
        \Artisan::call('passport:install');

        parent::_before($test); // TODO: Change the autogenerated stub
    }

}
