version: '2'
volumes:
  # MySQL Data
  maestro-mysql-data:
    driver: local
  # Redis Data
  maestro-redis-data:
    driver: local
services:
  web:
    #image: ambientum/php:7.0-caddy
    image: ambientum/php:7.3-nginx
    #image: ambientum/php:7.0-apache
    container_name: maestro-web
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    container_name: maestro-mysql
    volumes:
      - maestro-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=maestrodb
      - MYSQL_DATABASE=maestrodb
      - MYSQL_USER=maestrodb
      - MYSQL_PASSWORD=maestrodb
  # Redis
  redis:
    container_name: maestro-redis
    image: 'redis:4-alpine'
    command: redis-server --requirepass maestrodb
    volumes:
      - maestro-redis-data:/data
    ports:
      - "6370:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: maestro-phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
