version: '3'
volumes:
  maestro-mysql-data:
    driver: local

  maestro-redis-data:
    driver: local

  maestro-mongo-data:
    driver: local

services:
  web:
    image: ambientum/php:7.3-nginx
    container_name: maestro-web
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
  mysql:
    image: mysql:5.7
    container_name: maestro-mysql
    volumes:
      - maestro-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=maestro
      - MYSQL_DATABASE=maestro
      - MYSQL_USER=maestro
      - MYSQL_PASSWORD=maestro
  redis:
    container_name: maestro-redis
    image: 'redis:4-alpine'
    command: redis-server --requirepass maestro
    volumes:
      - maestro-redis-data:/data
    ports:
      - "6379:6379"
  mongo:
    container_name: maestro-mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=maestro
      - MONGO_INITDB_ROOT_PASSWORD=maestro
      - MONGO_INITDB_DATABASE=maestro
    volumes:
      - maestro-mongo-data:/data/db
    ports:
      - "27017:27017"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: maestro-phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=maestro
