version: '2'
volumes:
  maestro-mysql-data:
    driver: local

  maestro-redis-data:
    driver: local

  maestro-mongo-data:
    driver: local

services:
  web:
    image: ambientum/php:7.3-nginx
    container_name: maestro-web
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    container_name: maestro-mysql
    volumes:
      - maestro-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=maestrodb
      - MYSQL_DATABASE=maestrodb
      - MYSQL_USER=maestrodb
      - MYSQL_PASSWORD=maestrodb
  redis:
    container_name: maestro-redis
    image: 'redis:4-alpine'
    command: redis-server --requirepass maestrodb
    volumes:
      - maestro-redis-data:/data
    ports:
      - "6379:6379"
  mongo:
    container_name: maestro-mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=maestro
      - MONGO_INITDB_ROOT_PASSWORD=maestro
    ports:
      - "27017:27017"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: maestro-phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
