version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - 8000:80
    volumes:
      - .:/var/www
    depends_on:
      - psql
      - redis
  psql:
    image: postgres:10.4
    restart: always
    environment:
      - POSTGRES_DB=idez
      - POSTGRES_USER=idez
      - POSTGRES_PASSWORD=idez
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
    - redis-data:/data
volumes:
  psql-data:
  redis-data:
