#!/bin/sh

php /var/www/artisan migrate --force
php /var/www/artisan config:cache
php /var/www/artisan route:cache
php /var/www/artisan passport:keys
php /var/www/artisan queue:work --tries=5 --delay=15 &
php-fpm & cron & nginx -g "daemon off;"
