<?php

namespace App\Nova;

use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\ID;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Markdown;
use Laravel\Nova\Fields\Number;
use Laravel\Nova\Fields\Select;
use Laravel\Nova\Fields\Text;

class Vehicle extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = 'App\Vehicle';

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'model';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'plate', 'model'
    ];

    public static function label()
    {
        return 'Veículos'; // TODO: Change the autogenerated stub
    }

    public static $displayInNavigation = false;

    /**
     * Get the fields displayed by the resource.
     *
     * @param  Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable()->onlyOnForms(),
            BelongsTo::make('Transportadora', 'transporter', Transporter::class)
                ->searchable()
                ->size('w-1/4'),
            Select::make('Tipo')
                ->options([
                    'water' => 'Água',
                    'cement' => 'Cimento',
                    'cargo' => 'Baú',
                    'van' => 'Van',
                    'lowboy' => 'Lowboy',
                    'container' => 'Container',
                    'chemical' => 'Químico'
                ])->size('w-1/4'),
            Text::make('Modelo', 'model')->size('w-2/4'),
            Text::make('Placa', 'plate')->size('w-1/3'),
            Number::make('Capacidade', 'capacity')->size('w-1/3'),
            Number::make('Tamanho', 'length')->size('w-1/3'),
            Number::make('Eixos', 'axles')->size('w-1/5'),
            Text::make('Num. Frota', 'fleet_number')->size('w-2/5'),
            Text::make('Renavam','renavam')->size('w-1/5'),
            Markdown::make('Notas', 'notes')->size('w-full')
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
